services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: turing
      POSTGRES_PASSWORD: turing
      POSTGRES_DB: secret_santa
    ports:
      - '5433:5432'
    volumes:
      - secret_santa-db:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    environment:
      DATABASE_URL: postgres://turing:turing@postgres:5432/secret_santa
      PORT: 3000
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  # client:
  #   build:
  #     context: .
  #     dockerfile: ./client/Dockerfile
  #   environment:

  #     API_PROXY_PASS: http://server:3000
  #   ports:
  #     - '3001:80'
  #   depends_on:
  #     - server

volumes:
  secret_santa-db:
