/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export type Json = JsonValue

export type JsonArray = JsonValue[]

export type JsonObject = {
  [x: string]: JsonValue | undefined
}

export type JsonPrimitive = boolean | number | string | null

export type JsonValue = JsonArray | JsonObject | JsonPrimitive

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface Event {
  budgetLimit: number
  createdAt: Generated<Timestamp>
  createdBy: string
  description: string
  eventDate: Timestamp
  id: Generated<number>
  status: string
  title: string
  updatedAt: Generated<Timestamp>
}

export interface EventInvitations {
  createdAt: Generated<Timestamp>
  email: string
  eventId: number
  id: Generated<number>
  status: string
  updatedAt: Generated<Timestamp>
  userId: string | null
}

export interface EventRule {
  eventId: number
  id: Generated<number>
  ruleData: Json
  ruleType: string
}

export interface User {
  auth0Id: string
  createdAt: Generated<Timestamp>
  email: string
  firstName: string | null
  id: Generated<number>
  lastLogin: Generated<Timestamp>
  lastName: string | null
  picture: string | null
}

export interface UserEvent {
  createdAt: Generated<Timestamp>
  eventId: number
  eventTitle: string
  id: Generated<number>
  role: string
  santaForUserId: string | null
  updatedAt: Generated<Timestamp>
  userId: string
  wishlistId: number | null
}

export interface UserWishlist {
  createdAt: Generated<Timestamp>
  description: string
  id: Generated<number>
  title: string
  updatedAt: Generated<Timestamp>
  userId: string
}

export interface Wishlist {
  createdAt: Generated<Timestamp>
  description: string | null
  id: Generated<number>
  itemName: string
  price: number | null
  updatedAt: Generated<Timestamp>
  userId: string
  userWishlistId: number
}

export interface DB {
  event: Event
  eventInvitations: EventInvitations
  eventRule: EventRule
  user: User
  userEvent: UserEvent
  userWishlist: UserWishlist
  wishlist: Wishlist
}
